### PR TITLE
add region to intrastat_product

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by alexis-via** [comment]
It seems that it lacks:
- the addition of the region field in the form view of the invoice (as invisible)
- the view of the region itself (form/tree/action/menu)

**Comment by alexis-via** [comment]
And also the ACL !

**Comment by alexis-via** [comment]
By the way, are you sure we should put a "company_id" field on the region ?

And why do you put a region field on the products ? Region is supposed to be related to the stock location or warehouse (source region for dispatches / destination region for arrivals)

**Comment by luc-demeyer** [comment]
The move of region from l10n_be_intrastat_product to intrastat_product was indeed incomplete.
I have now fixed this
- hashcode updated
- region_id on computation and declaration lines
- region_id on warehouse
- security group & acl

**Comment by luc-demeyer** [comment]
Concerning company_id on region: i think we can indeed drop it.
Concerning region on products: I don't put region ,on products but on warehouse.

**Comment by luc-demeyer** [comment]
For the latest version of the Belgian localisation module (which assumes that the region field is in the intrastat_product module), cf. https://github.com/Noviat/l10n-belgium/tree/8.0-add-intrastat

**Comment by alexis-via** [comment]
Thanks. On my side, I need 2 additional fields on declaration/computation lines:
- partner_id (to get the VAT number of the partner)
- product_country_origin_id (product made in "Taiwan")
  I'll add them as invisible. The only drawback for you is that I will splits the grouping by partner and product_country_origin_id... but you can inherit the grouping method in your l10n_be module with a check on company_id.country_id.code == 'BE'

For the rest, I'm progressing on l10n_fr_. I need to have something working for thursday night !

**Comment by luc-demeyer** [comment]
@alexis-via 
comments on the 2 additional fields:
1) VAT number of the partner: only 2 of the 27 member states require this in the intrastat declaration (FR and LV) hence it could be better to add the partner_id to the computation lines of the l10n_fr_\* module (idem for hashcode
2) product_country_origin_id: required by 21 of the 27 member states hence the field should be in the intrastat_base module. In order to facilitate the customisation of the hashcode in the localisation modules I propose that we split the hashcode method into two parts: 
- part 1; a list of elements with to be included in the hashcode (hence the localisation modules can easily add/remove elements from the list
- part 2: the creation of the hashcode string based upon this list
  If you agree with this proposal; will you implement it or shall I make a PR ?

**Comment by alexis-via** [comment]
1) You said in a previous comment on this PR https://github.com/akretion/account-financial-reporting/pull/6 "move it into the intrastat_product module [...] for every field which is common to more than 1 country." So now you say that, as it's used by only 2 countries, let's put it in l10n__intrastat. What's your opinion on this exactly ? I'm OK to put it in l10n_fr_intrastat_ (in this case, I would call the field fr_partner_id' to avoid collision with a future l10n_lv_intrastat module), but we need to decide what's our policy on this.
2) I'll put the field 'product_country_origin_id' on declaration+computation lines in intrastat_product (it's already present on product.template in the module "product_harmonized_system").

I agree with your proposal for the hascode method. I won't have time to do it myself because I'm too busy on l10n_fr_intrastat_product and l10n_fr_intrastat_service with my deadline for Thursday !

**Comment by luc-demeyer** [comment]
@alexis-via 
1) Based upon your feedback (on my '>1 country' suggestion ) I propose that we decide on a case-by-case basis for the best place to put a certain field. I leave it up to you to decide if you want to put the partner_id field in the localisation module declaration_lines or the intrastat_product. 
2) I'll make a PR to refactor the hashcode.

**Comment by alexis-via** [comment]
1) OK for a case-by-case basis, I agree with that.
2) OK, great.

**Comment by alexis-via** [comment]
Do we need the "description" field on the intrastat region ? What is it for ? I think "name" + "code" are enough.

By the way, as wa said that partner_id is kept in l10n.fr, I moved back the fiscal representative to l10N_fr.

**Comment by alexis-via** [comment]
Why is _get_region not called anywhere in intrastat_product ?

**Comment by luc-demeyer** [comment]
1) do we need "description" in region ?
Yes, cf. data/intrastat_region.xml in l10n_be_intrastat_product for an example of the usage of this field.

2) I am calling get_region in l10n_be_intrastat_product. The advantage of not calling _get_region in intrastat_product is that localisation modules that do not require this optional field do not need to adapt the hashcode.

**Comment by alexis-via** [comment]
1) OK

2) I think that we can include the call to _get_region in the module intrastat_module, to make things easier in the localisation modules. The localisation modules that don't required this field will not provide the required data and will keep the field invisible, and that won't be a problem for them I think.

**Comment by luc-demeyer** [comment]
@alexis-via 
2) if you are in a multi_company/multi_country setup your warehouses will probably be configured with regions since 30% of member states require this field, hence having the _get_region in intrastat_product module will populate the computation_lines and will require the localisation modules to remove the field from the hashcode (like I have now done for the 'product_origin_country' field which is not required for BE).
Hence you make it easier for some localisation modules and harder for others.
An option that we could put on the roadmap is to refactor the intrastat_product module and define a matrix with standard fields and extended declaration fields per member state.
This will make it 'super-easy' for the localisation modules but will take some time to implement (could be an idea for code sprint during 2016 Open Days).

**Comment by alexis-via** [comment]
I think of a better solution: make it super-easy to inherit the methods of the module intrastat_product in localisation modules : for that, all methods of intrastat_product/models/intrastat_product_declaration.py should have a "company_coutry_code" argument that contain the code of the country of the company. So, if a the spanish intrastat declaration of a country doesn't have regions, he can do:

```
if company_country_code = 'ES':
    # remove region from hash code
```

**Comment by alexis-via** [comment]
I still miss 2 importants things in the module intrastat_product compared to what I used to have in my old modules:
1) The possibility to set default values for intrastat.transaction for customer invoice, customer refunds and supplier invoices
2) Take into account the shipping costs in the computing of the fiscal value

**Comment by luc-demeyer** [comment]
concerning company_country_code : good idea to add it as a related field but it will not make a lot of difference in the localisation modules. Now I use self.company_id.country_id.code == 'BE' with the related field the comparison will be a few characters shorter.

concerning missing things:
1) default transaction: could be good idea to add default parameters on res_company and adapt the def _default_intrastat_transaction method for a lookup on res_company.
2) shipping costs: I think this applies only to France hence should be part of your localisation module. The purpose of intrastat product declaration is trading statistics on goods. Your french declaration seems to add a VAT/Tax element to this declaration (which is covered by separate intracomm declarations in other countries), hence this may explain why french authorities want shipping costs.

**Comment by alexis-via** [comment]
1) done
2) I thought you, in Belgium, you had a check between the total of your UE sales without taxes (VAT declaration) and your instrastat ? If so, you need to have the ship costs inside the fiscal amount of the goods. I would be very surprised if this is something specific to France.

Other important things:
3) you didn't take into account the boolean exclude_from_intrastat_if_present from taxes, in order to exclude B2C sales (that include Belgian taxes) from intrastat declaration -> I added it.
4) When you create an invoice from delivery or from SO, the 'hs_code_id' field is not set on the invoice line, because odoo doesn't play the onchange ! So all the 'hs_code_id' are empty on invoice lines, and therefore the declaration is empty ! What is your plan on this ? Should we leave the hs_code_id field empty on invoice lines and do in the code the generate the computation lines:

```
if inv_line.hs_code_id:
  -> use this
elif inv_line.product_id.product_tmpli_id.get_hs_code_recursively():
  -> use that one
```

**Comment by alexis-via** [comment]
About 4)
If think that the code sample I propose is the best solution, and the hs_code_id field on invoice line should only be used to "Force" a specific HS code on the invoice line. The big advantage is that we avoid an inherit of the numerous methods that create invoice lines (from delivery, from SO, from PO, from PO line, etc....)

What do u think ? I already implemented it in the local repo.

**Comment by luc-demeyer** [comment]
2) Shipping costs
Shipping costs are SERVICES and Belgian Intrastat declaration guidelines EXPLICITLY state that these costs are NOT part of the intrastat declaration (except if it's technically impossible to split them out, e;g. when shipping costs are "free", i.e. included in the product price). It's strange that France and Belgium impose on a completely different way the same European Intrastat Guidelines.

Concerning VAT declaration cross check: shipping costs are services and reported on another vat case in the Belgian declaration than goods, hence adding shipping cost would also break the cross-check. 

I also didn't find shipping cost in the EU document showing the matrix of required and optional elements per member state, hence I think it's a pure French requirement. 

From a practical standpoint I propose to put it in the French localisation and move it to the common code whenever we find out that it applies to multiple countries.

3) exclude_from_intrastat_if_present 
Since you have this boolean in intrastat_base, intrastat_product indeed needs to take this boolean into account. This may again be a pure French requirement since in Belgium we need to declare ALL in- and outgoing goods B2C as well as B2B (Intrastat is for STATISTICS not for taxes, I am again surprised to see this difference between our two countries, how can the French governement have an idea of goods moving between memberstates if B2C is excluded ? Is there another declaration covering that ?

4)  invoice from delivery or from SO
I agree with the way you fixed this in your local repo, please merge this fix into your PR.

**Comment by alexis-via** [comment]
2) Let's just make it an option on res.company "Add account accessory costs to fiscal value of products". This option would be unactive by default. I'll implement that in the coming days.

3) Strange. In France, we declare only the goods that are sold without VAT (B2B) and not the ones sold with French VAT (B2C with turnover under the limit)

4) Yes, i'll merge your PR #8  in the coming days.

**Comment by luc-demeyer** [comment]
2) Add account accessory costs to fiscal value of products
Can you put invisible=1 in intrastat_product for this res_company option (hence up to the localisatin modules to make it visible)

3) exclude_from_intrastat_if_present on taxes
I would also prefer to have this one invisible in intrastat_base

**Comment by alexis-via** [comment]
2) OK, the option will be invisible

3) OK, invisible too

**Pull request merged**
