### PR TITLE
major update intrastat V3 modules

### PR DESCRIPTION
**Pull request by luc-demeyer**
Update modules in branch 8.0-update-instrastat-v3:
-   Refactor base modules (bugfixes, new OCA coding guidelines)
-   Add l10n_be_intrastat_product

### CODE REVIEW

**Comment by alexis-via** [comment]
Thanks for your work.

I'll remove l10n_be_intrastat_product, as it's againt OCA's rules to have a country-specific module outside of l10n-country. So you'll have a make a PR on l10n-belgium for that.

**Comment by luc-demeyer** [comment]
Thanks.
I'll make the PR for l10n-belgium but it easier to wait until this one is merged into account-financial-reporting. Can you remove the "work in progress" label on the intrastat-V3 label in order to proceed with the merge ?

**Comment by alexis-via** [comment]
I see that intrastat region is still in your specific BE module. I thought you wanted to put it in intrastat.product (you told me this by email in the past)... did you change your mind ? In fact, maybe a module intrastat_product_region would be the best solution, because you told me that "only" 30% of the EU countries need it.

If everything goes as planned, I'll be working on intrastat today and next week, so I'll remove the work in progress flag at the end of my work, because I may want to changes a few things. But I'll tell you about it before, to have your agreement before any significant modification.

**Comment by luc-demeyer** [comment]
Concerning region:
I prefer to move it into the intrastat_product module since it is common to 30% of the countries and I would like to follow this road for every field which is common to more than 1 country. Using the "intrastat_product_region" approach will lead to too many modules and will become hard to manage.

In the intrastat_product module we define the views for the optional common fields with invisible=1 hence making it easy for the localisation modules to enable the feature by a simple view inherit..
If you agree with this approach, than I'll make a PR (later today and in any case before the end of the weekend because I am activatin the new intrastat at a pilot customer on monday).

**Comment by alexis-via** [comment]
I may say that the rule to add automatically a field in intrastat_product "for every field which is common to more than 1 country" seems a bit "too much for me". I prefer the rule "for every field which is common to more than 1 country, we will study if we include it in intrastat_product OR in a dedicated module instead". For the intrastat.region, I'm ok to include it in intrastat_product with invisible="1", even if putting it a separate module would have been a good option too IMHO.

**Comment by alexis-via** [comment]
It seems we didn't put this field on res.partner in intrastat_product:

```
intrastat_fiscal_representative = fields.Many2one(
        'res.partner', string="EU fiscal representative",
        help="If this partner is located outside the EU but you "
        "deliver the goods inside the UE, the partner needs to "
        "have a fiscal representative with a VAT number inside the EU. "
        "In this scenario, the VAT number of the fiscal representative "
        "will be used for the Intrastat Product report (DEB).")
```

Are you OK if I put it in intrastat_product ? The details are here: http://bazaar.launchpad.net/~new-report-intrastat-team/new-report-intrastat/trunk/view/head:/l10n_fr_intrastat_product/partner.py

**Comment by luc-demeyer** [comment]
@alexis-via 
1) ok for intrastat_fiscal_representative
2) I moved region into intrastat_product, cf. PR https://github.com/akretion/account-financial-reporting/pull/7

**Pull request merged**
