### PR TITLE
refactor hashcode

### PR DESCRIPTION
**Pull request by luc-demeyer**

### CODE REVIEW

**Comment by luc-demeyer** [comment]
PR with refactor hashcode plus a couple of other changes:
- _init__.py: fix double import of account_invoice.py + alfabet sort (cf. OCA guidelines)
- remove "if True" from _get_weight_and_supplunits + fixed error check (weigth on product record is optional in case of suppl unit)
- remove region logic (better in localisation module and if we want to keep in in intrastat_product than we should create a section for 'optional' elements. This field should not be part of extended elements since e.g. for Belgium it is mandatory for standard and extended declaration.
- remove remark on delete "Notes" field add recompute. I think we should leave it up to the end user to clean up the Notes field (it is possible that the end user has manually documented some of the actions taken on the declaration hence we should preserve this).

I have also updated the belgian localization module for the refactored hashcode,
cf https://github.com/Noviat/l10n-belgium/tree/8.0-add-intrastat

**Comment by alexis-via** [comment]
I agree with all your changes except one: the call to _get_region should be in intrastat_product, so as to simplify the localisation modules. It is not a problem for the countries that don't use it because they won't provide the data for the objects intrastat.region and the region fields will stay invisible.

**Comment by alexis-via** [comment]
I merged your code. As this PR had conflicts, I incorporated the changes directly in akretion:8.0-add-intrastat-v3. The only thing that I didn't incorporate is the change of 

```
if not product.weight_net:
```

to

```
if not product.weight_net and not intrastat_unit_id: 
```

I didn't understand why you made this change and I think it's wrong, at least for France (and maybe other countries) : we have to indicate both the weight and the supplementary unit (but I think you told me it was not the case in Belgium).

**Comment by luc-demeyer** [comment]
@alexis-via 
Thanks for merging my PR.

Concerning your refusal for the "if not product.weight_net and not intrastat_unit_id" change:
It will generate a (maybe somewhat confusing) warning to the Belgian users since weight is optional in Belgium in case of supplementary units but on the other hand, the Belgian specs do not forbid to report weight and from an 'multi-country / shared product records' implementation standpoint it's better to stimulate our customers to have the correct weight on their product records.
Hence I agree with your standpoint (at least for the time being since I am not sure if France or Belgium is the exception here).

**Pull request closed without merging**
